### ISSUE TITLE
[Feature Request] Extend the solution to add consideration of _spf.google.com

### ISSUE THREAD

**Issue by DazWilkin** [hm-distro/netblocks#3]
The solution supports enumeration of the IP addresses used by GCP and summarized [here](https://cloud.google.com/compute/docs/faq#where_can_i_find_product_name_short_ip_ranges) but it does not include peripheral Google services including e.g. GCS, Drive and (indirectly) summarized [here](https://support.google.com/a/answer/60764) as Google's Sender Policy Framework for Gmail.

Recommend: Extend the solution to support the _spf.google.com addresses
 - either (by default) enumerate the union of these netblocks
 - or by surfacing a selector for the user to decide cloud, spf, cloud & spf

**Comment by hm98765** [comment]
done
